// antes foi instalada a extensão REST Client que ajuda a criar rotas

// os métodos abaixo servem para enviar dados para a requisição

POST https://praticando-nodejs.onrender.com/videos
Content-Type: application/json

{
  "title": "Don't blame me Music Video",
  "description": "Music video by Taylor Swift",
  "duration": 13
}

###

GET https://praticando-nodejs.onrender.com/videos

###

PUT https://praticando-nodejs.onrender.com/videos/865bfa55-6189-4af7-8aea-ba869658e129
Content-Type: application/json

{
  "title": "Dress Music Video",
  "description": "Music video by Taylor Swift",
  "duration": 13
}

###

DELETE https://praticando-nodejs.onrender.com/videos/865bfa55-6189-4af7-8aea-ba869658e129
